# Generated by Django 3.2.7 on 2021-10-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Machine Learning', 'Machine Learning'), ('Web Dev', 'Web Dev'), ('Research', 'Research')], max_length=250, null=True),
        ),
    ]
