# Generated by Django 3.2.7 on 2021-10-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.AddField(
            model_name='project',
            name='category1',
            field=models.CharField(choices=[('Machine Learning', 'Machine Learning'), ('Web Dev', 'Web Dev'), ('Research', 'Research')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='category2',
            field=models.CharField(choices=[('Computer Vision', 'Computer Vision'), ('Django 3.0', 'Django 3.0'), ('Other', 'Other')], max_length=250, null=True),
        ),
    ]
