# Generated by Django 3.2.7 on 2021-10-09 12:02

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_visit_profile_pic'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='visit',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='visit',
            name='name',
            field=models.CharField(default='Update your name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='phone',
            field=models.CharField(default='Update your phone number', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to=''),
        ),
    ]
