# Generated by Django 3.2.7 on 2021-10-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211009_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='firstname',
            field=models.CharField(default='Update your first name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='lastname',
            field=models.CharField(default='Update your last name', max_length=200, null=True),
        ),
    ]
